/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dd_jni_common_StringChild */

#ifndef _Included_com_dd_jni_common_StringChild
#define _Included_com_dd_jni_common_StringChild
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_initNative
  (JNIEnv *, jclass);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    print
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dd_jni_common_StringChild_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    getIntField
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dd_jni_common_StringChild_getIntField
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    setStringFiled
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_setStringFiled
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    callJavaMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_callJavaMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    NewJavaObject
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_NewJavaObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    CallBasisArray
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dd_jni_common_StringChild_CallBasisArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    CallObjectArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_CallObjectArray
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    nativeAddOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_nativeAddOne
  (JNIEnv *, jobject);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    nativeMinusOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_nativeMinusOne
  (JNIEnv *, jobject);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    getNativeValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dd_jni_common_StringChild_getNativeValue
  (JNIEnv *, jobject);

/*
 * Class:     com_dd_jni_common_StringChild
 * Method:    createNativeThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dd_jni_common_StringChild_createNativeThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
